### PR TITLE
bug: #39 remove cloudfront duplicate on samba page

### LINKED ISSUE #39: Cloudformation section behaves inconsistently
The only page where it looks good is the Rsyslog, if you click on other pages, you will see that some tiems you have two of them, some times other stuff is happening that is wierd etc.

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Remove duplicate CloudFront section on Samba page

Closes #39

### CODE REVIEW

**Comment by davidgatti** [comment]
Can you explain how you made this module? point to some URL in the project, because I think I understand why I'm confused and you are not :)

**Comment by acidbiscuit** [comment]
@davidgatti [Here](https://github.com/0x4447-office/0x4447_webpage_documentation/blob/bug/%2339-remove-cloudfront-duplicate-on-samba-page/docs/.vuepress/components/CloudFormation.vue) is the component that renders CloudFormation section

**Comment by davidgatti** [comment]
OK, so how is this section inside the component? 

Screen Shot 2021-04-25 at 3 20 30 PM

**Comment by acidbiscuit** [comment]
@davidgatti CloudFormation section only includes "Launch Stack" image and text starting with "We provide a complementary...". The rest of the content was already on the page, so I did not touch it.   
Title "CloudFormation" has to be outside of the component to be recognized in the sidebar navigation.

**Comment by davidgatti** [comment]
Aaaa so there is no way to include also the header part itself?

**Comment by acidbiscuit** [comment]
@davidgatti Nope. It is not currently supported with automatically generated sidebar.

**Comment by davidgatti** [comment]
OK, in this case I will rethink how I want to go about this.

**Pull request closed without merging**
