### PR TITLE
Vv/#64 add code block copy to clipboard

### LINKED ISSUE #64: Add copy to clip board
It be nice to have.

Screen Shot 2021-05-15 at 3 29 05 PM

### PR DESCRIPTION
**Pull request by acidbiscuit**
- Add code block copy to clipboard button

Closes #64

### CODE REVIEW

**Review by davidgatti — CHANGES_REQUESTED** [review]
- you included the search features
- now the code section has an extra line, margin, space whatever we want to call it :)

Screen Shot 2021-05-24 at 6 32 01 AM

**Comment by acidbiscuit** [comment]
@davidgatti Issues resolved

**Review by davidgatti — CHANGES_REQUESTED** [review]
Now there is a scroll bar even if it is unnecessary - @acidbiscuit please run the code locally and check it out before commuting :)

Screen Shot 2021-05-24 at 12 20 26 PM

**Comment by acidbiscuit** [comment]
@davidgatti Give it a try.

**Pull request merged**
